// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFbl8KZI_36XQZrsBZx6hOsMCXTTUr4X4',
    appId: '1:557841316955:web:e9c9dc965e6a4f1bab537e',
    messagingSenderId: '557841316955',
    projectId: 'connecty-3e62d',
    authDomain: 'connecty-3e62d.firebaseapp.com',
    storageBucket: 'connecty-3e62d.firebasestorage.app',
    measurementId: 'G-04P6RW25WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYisRmqikF9JCPAw0K7-7-8qUJ6-lw8r4',
    appId: '1:557841316955:android:ac012918e534456dab537e',
    messagingSenderId: '557841316955',
    projectId: 'connecty-3e62d',
    storageBucket: 'connecty-3e62d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuEx4RihsYoLGJkeFL1g6-6AlonJn0IvE',
    appId: '1:557841316955:ios:cd0db95089086ee6ab537e',
    messagingSenderId: '557841316955',
    projectId: 'connecty-3e62d',
    storageBucket: 'connecty-3e62d.firebasestorage.app',
    iosBundleId: 'com.example.connectyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuEx4RihsYoLGJkeFL1g6-6AlonJn0IvE',
    appId: '1:557841316955:ios:cd0db95089086ee6ab537e',
    messagingSenderId: '557841316955',
    projectId: 'connecty-3e62d',
    storageBucket: 'connecty-3e62d.firebasestorage.app',
    iosBundleId: 'com.example.connectyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFbl8KZI_36XQZrsBZx6hOsMCXTTUr4X4',
    appId: '1:557841316955:web:5a2a96ba3ef69133ab537e',
    messagingSenderId: '557841316955',
    projectId: 'connecty-3e62d',
    authDomain: 'connecty-3e62d.firebaseapp.com',
    storageBucket: 'connecty-3e62d.firebasestorage.app',
    measurementId: 'G-RLVRXDJRTV',
  );
}
